title: HRT Cat

theme: just-the-docs
color_scheme: dark
logo: "/assets/images/trickster.png"

version: 1.2
updated: "September 2, 2024"

banner: "This website is a public archive of hrt.cat hosted by @asleepyskye at vixen.lgbt. @asleepyskye is not affiliated with the original authors, and does not guarantee safety/validity of the information posted (though this page is a copy of the last published version on git.gay/hrtcat/pages)."

url: https://hrt.cat

plugins:
  - jekyll-redirect-from

callouts:
  warning:
    title: Warning
    color: red
  caution:
      title: Caution
      color: yellow
  info:
    title: Info
    color: blue
  notice:
    title: Notice
    color: green
