title: HRT Cat

theme: just-the-docs
color_scheme: dark
logo: "/assets/images/trickster.png"

version: 1.2
updated: "July 23, 2024"

# banner: "Notice: Please bookmark our backup domain, hrtcat.org"

url: https://hrt.cat

plugins:
  - jekyll-redirect-from

callouts:
  warning:
    title: Warning
    color: red
  caution:
      title: Caution
      color: yellow
  info:
    title: Info
    color: blue
  notice:
    title: Notice
    color: green
